Jupiter Terminal Integration user guide + demo
jup-ag/space-station pull request #106
Opened 2023-06-05 09:42 UTC by benlvb

2023-06-05 11:16 UTC, dongnguyen9186 approved these changes

2023-06-05 11:17 UTC, dongnguyen9186 commented
@benlvb  can you move images into static folder?

2023-06-05 11:18 UTC, dongnguyen9186 requested changes
can you move images into static folder?

2023-06-05 20:20 UTC, Timoon21 reviewed
Currently, “guides” section is “user oriented” and “docs” section is “technical docs”.

Jup terminal integration seems more a “technical docs”. Have you considered create a “tutorial” section in the docs instead?

Other than that, this guide is okay for me.

2023-06-05 20:20 UTC, Timoon21 reviewed
Currently, “guides” section is “user oriented” and “docs” section is “technical docs”.

Jup terminal integration seems more a “technical docs”. Have you considered create a “tutorial” section in the docs instead?

Other than that, this guide is okay for me.

2023-06-06 03:58 UTC, dicksonpys commented on guides/8-terminal-integration-guide.md
> +[Watch tutorial on YouTube](https://youtu.be/T-3KN3k1e5Y)
awesome, simple, short, and concise

2023-06-06 03:59 UTC, dicksonpys approved these changes
thanks for addressing your engineer's camera shyness, approved on my side 👍

2023-06-07 03:02 UTC, dongnguyen9186 approved these changes

2023-06-07 03:02 UTC, merged